# ****WEB SCRAPING ASSIGNMENT 3*********

In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\nirma\anaconda3\lib\site-packages (4.7.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: trio~=0.17 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: sniffio in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: cffi>=1.14 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: outcome in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sortedcontainers in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: pycparser in c:\users\nirma\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\nirma\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\nirma\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\nirma\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [4]:
import selenium 
import pandas as pd
from selenium import webdriver

import warnings 
warnings.filterwarnings('ignore')

from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException

from selenium.webdriver.common.by import By
import time

from PIL import Image
import io
import requests

# Q1

1. Write a python program which searches all the product under a particular product from www.amazon.in. The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for guitars.

In [126]:
driver=webdriver.Chrome('chromedriver.exe')

In [127]:
driver.get("https://www.amazon.in./")
time.sleep(5)

In [129]:
user_input=input("enter the product:")
print(user_input)

enter the product:guitar
guitar

In [130]:
search_bar = driver.find_element(By.ID,"twotabsearchtextbox")
search_bar.send_keys(user_input)

In [131]:
search_button = driver.find_element(By.XPATH,'//div[@class="nav-search-submit nav-sprite"]')
search_button.click()

# Q2

2. In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then scrape all the products available under that product name. Details to be scraped are: "Brand Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and “Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [132]:
# scrape all product url
product_url = []
start=0
end=3
for page in range(start,end):                                                 
    url=driver.find_elements(By.XPATH,'//a[@class = "a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]') #scraping urls      
    for i in url:
        product_url.append(i.get_attribute("href"))                        
    next_button=driver.find_element(By.XPATH,'//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]') 
    next_button.click()
    time.sleep(2)

In [133]:
len(product_url)

200

In [134]:
Brand_Name=[]
Name_of_Product=[]
Price=[]
Return_Exchange=[]
Expected_Delivery=[]
Availability=[]


for url in product_url[0:20]:
    driver.get(url)
    time.sleep(2)
    
    try:  #Brand_Name                       
        brand= driver.find_element(By.XPATH,'//*[@id="productOverview_feature_div"]/div/table/tbody/tr[1]/td[2]/span')
        Brand_Name.append(brand.text)
    
    except NoSuchElementException as e:
         Brand_Name.append('-')
            
            
    
    try:  #Name_of_Product   
        product= driver.find_element(By.XPATH,'//span[@class="a-size-large product-title-word-break"]')
        Name_of_Product.append(product.text)
    
    except NoSuchElementException as e:
         Name_of_Product.append('-')
            
            
            
    try:   #Price
        product_price= driver.find_element(By.XPATH,'//span[@class="a-price aok-align-center reinventPricePriceToPayMargin priceToPay"]')
        Price.append(product_price.text)
    
    except NoSuchElementException as e:
         Price.append('-')
              
        
            
    try:   #Return_Exchange
        exchange= driver.find_element(By.XPATH,'//*[@id="RETURNS_POLICY"]/span/div[2]/a')
        Return_Exchange.append(exchange.text)
    
    except NoSuchElementException as e:
         Return_Exchange.append('-')
            
            
            
    try:   #Expected_Delivery
        delivery= driver.find_element(By.XPATH,'//span[@class="a-text-bold"]')
        Expected_Delivery.append(delivery.text)
    
    except NoSuchElementException as e:
         Expected_Delivery.append('-')
            
            
            
    try:   #Availability
        avail= driver.find_element(By.XPATH,'//div[@id="availability"]')  
        Availability.append(avail.text)
    
    except NoSuchElementException as e:
         Availability.append('-')

In [136]:
print(len(Brand_Name),len(Name_of_Product),len(Price),len(Return_Exchange),len(Expected_Delivery),len(Availability))

20 20 20 20 20 20

In [139]:
df=pd.DataFrame({'Brand':Brand_Name,'ReturnExchange':Return_Exchange,'Price':Price,'Delivery_by':Expected_Delivery,'Name of Product':Name_of_Product,'Availability of product':Availability,'urls':product_url[0:20]})
df

,Brand,ReturnExchange,Price,Delivery_by,Name of Product,Availability of product,urls
0,Kadence,7 days Replacement,"₹4,949","Sunday, 5 February",Kadence Frontier guitar with Online Guitar lea...,In stock.,https://www.amazon.in./sspa/click?ie=UTF8&spc=...
1,VAULT,7 days Replacement,"₹4,669","Tuesday, 7 February",Vault DA20 Dreadnought Acoustic Guitar With Gi...,In stock.,https://www.amazon.in./sspa/click?ie=UTF8&spc=...
2,Multi-coloured,7 days Replacement,₹899,"Tuesday, 7 February",Hontral S4 String Decor Guitar Children's Musi...,In stock.,https://www.amazon.in./sspa/click?ie=UTF8&spc=...
3,Generic,7 days Returnable,"₹9,990","Thursday, 9 February",THE MUSIC WORLD - ACOUSTIC GUITAR F310,Only 1 left in stock.,https://www.amazon.in./sspa/click?ie=UTF8&spc=...
4,JUAREZ,7 days Replacement,"₹2,090","Monday, 6 February","Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...",In stock.,https://www.amazon.in./Juarez-Acoustic-Cutaway...
5,Intern,7 days Replacement,"₹2,349","Tuesday, 7 February","Intern INT-38C Right hand Acoustic Guitar Kit,...",In stock.,https://www.amazon.in./Intern-INT-38C-Acoustic...
6,YAMAHA,7 days Replacement,"₹7,421","Thursday, 9 February","Yamaha F280 Acoustic Rosewood Guitar (Natural,...",Only 1 left in stock.,https://www.amazon.in./Yamaha-F280-Acoustic-Gu...
7,Fender,7 days Replacement,"₹12,999","Tuesday, 7 February",Fender Dreadnought CD 60 Dread V3 DS 6 String ...,Only 2 left in stock.,https://www.amazon.in./Fender-Dread-String-Aco...
8,YAMAHA,7 days Replacement,"₹9,490","Sunday, 5 February","Yamaha FS100C Acoustic Guitar, Natural",In stock.,https://www.amazon.in./Yamaha-FS100C-Acoustic-...
9,HOVNER,7 days Replacement,"₹4,480","Tuesday, 7 February",Hovner 215 Black F-Cut Rosewood Fretboard Acou...,In stock.,https://www.amazon.in./Rosewood-Fretboard-Acou...
10,Kadence,7 days Replacement,"₹7,874","Sunday, 5 February","Kadence Guitar Acoustica Series, 41” Jumbo Siz...",In stock.,https://www.amazon.in./Kadence-6-strings-Acous...
11,Intern,7 days Replacement,"₹2,099","Sunday, 5 February",Intern 38C Ebony Wood Cutaway Design Acoustic ...,In stock.,https://www.amazon.in./Intern-38-inch-Cutaway-...
12,JUAREZ,7 days Replacement,"₹2,704","Monday, 6 February",JUAREZ JRZ38C 38 Inches Lindenwood Right Hande...,In stock.,https://www.amazon.in./JUAREZ-JRZ38C-Acoustic-...
13,Kadence,7 days Replacement,"₹5,399","Sunday, 5 February","Kadence rosewood Guitar Frontier Series, Elect...",In stock.,https://www.amazon.in./Kadence-Frontier-Acoust...
14,JUAREZ,7 days Replacement,"₹2,372\n09","Sunday, 5 February","Juarez Lindenwood Acoustic Guitar, 38 Inches C...",In stock.,https://www.amazon.in./Juarez-Acoustic-Guitar-...
15,HOVNER,7 days Replacement,"₹4,480","Tuesday, 7 February",Hovner 215 Black F-Cut Rosewood Fretboard Acou...,In stock.,https://www.amazon.in./Rosewood-Fretboard-Acou...
16,YAMAHA,7 days Replacement,"₹9,990","Sunday, 5 February","Yamaha FS100C Acoustic Guitar, Black",In stock.,https://www.amazon.in./Yamaha-FS-100C-6-String...
17,JUAREZ,7 days Replacement,"₹2,109","Monday, 6 February","Juarez Acoustic Guitar, [LEFT HANDED] 96.52 cm...",In stock.,https://www.amazon.in./Acoustic-Cutaway-TBLS-S...
18,JUAREZ,7 days Replacement,"₹2,504","Tuesday, 7 February","Juarez Lindenwood Acoustic Guitar Kit, 38 Inch...",In stock.,https://www.amazon.in./JUAREZ-JRZ38C-Acoustic-...
19,Medellin,7 days Replacement,"₹2,349","Sunday, 5 February",Medellin M38 carbon fiber body 38 Incheses Aco...,In stock.,https://www.amazon.in./Medellin-Acoustic-Guita...

# Q3

Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [34]:
driver3=webdriver.Chrome('chromedriver.exe')

In [35]:
driver3.get("https://images.google.com/")
time.sleep(5)

In [36]:
search_bar = driver3.find_element(By.XPATH,'//input[@class="gLFyf"]')    
search_bar.send_keys("fruits")

In [43]:
search_button = driver3.find_element(By.XPATH,'//span[@class="z1asCe MZy1Rb"]')    
search_button.click()

In [44]:
images = driver3.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')
print(len(images))

48

# Q4

4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [ ]:
driver4=webdriver.Chrome('chromedriver.exe')
driver4.get("https://www.flipkart.com/")
time.sleep(2)
driver4.maximize_window()
pop_close = driver4.find_element("xpath","/html/body/div[2]/div/div/button").click()
product = input(" Enter the name of Smartphone that has to be searched : ")
search_product4=driver4.find_element(By.CLASS_NAME,'_3704LK').send_keys(product)

# Q5

5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [27]:
driver5=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# opening google maps web page
driver5.get("https://www.google.co.in/maps")
driver5.maximize_window()
time.sleep(2)

#Sending keyword for seach box and search button
city = input('Enter City name to search : ')
search_city = driver5.find_element(By.ID,"searchboxinput")                       
search_city.clear()                                                             
time.sleep(2)

search_city.send_keys(city)                                                     
search_button = driver5.find_element(By.ID,"searchbox-searchbutton").click()                                                             
time.sleep(3)
Location=driver5.current_url

try:
    coordinates=re.findall(r'@(.*)data',Location)
    lat_lon=coordinates[0].split(",")
    lat=lat_lon[0]
    lon=lat_lon[1]
except IndexError as e:
    coordinates=re.findall(r'@(.*)z',Location)
    lat_lon=coordinates[0].split(",")
    lat=lat_lon[0]
    lon=lat_lon[1]
print("\nlatitude={}".format(lat))
print("\nlongitude={}".format(lon))

Enter City name to search : Delhi

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="searchboxinput"]"}
  (Session info: chrome=109.0.5414.75)
Stacktrace:
Backtrace:
	(No symbol) [0x00AF6643]
	(No symbol) [0x00A8BE21]
	(No symbol) [0x0098DA9D]
	(No symbol) [0x009C1342]
	(No symbol) [0x009C147B]
	(No symbol) [0x009F8DC2]
	(No symbol) [0x009DFDC4]
	(No symbol) [0x009F6B09]
	(No symbol) [0x009DFB76]
	(No symbol) [0x009B49C1]
	(No symbol) [0x009B5E5D]
	GetHandleVerifier [0x00D6A142+2497106]
	GetHandleVerifier [0x00D985D3+2686691]
	GetHandleVerifier [0x00D9BB9C+2700460]
	GetHandleVerifier [0x00BA3B10+635936]
	(No symbol) [0x00A94A1F]
	(No symbol) [0x00A9A418]
	(No symbol) [0x00A9A505]
	(No symbol) [0x00AA508B]
	BaseThreadInitThunk [0x75B87D69+25]
	RtlInitializeExceptionChain [0x7700BB9B+107]
	RtlClearBits [0x7700BB1F+191]

# Q6

6. Write a program to scrap details of all the funding deals for second quarter (i.e Jan 21 – March 21) from trak.in

In [40]:
driver=webdriver.Chrome('chromedriver.exe')
time.sleep(3)


url = "https://trak.in/"
driver.get(url)
time.sleep(2)

In [41]:
button = driver.find_element(By.XPATH,'//li[@id="menu-item-1237902"]/a').get_attribute('href')
driver.get(button)

In [42]:
date=[]
name=[]
industry=[]
subvertical=[]
location=[]
investors_name=[]
investors_type=[]
amount=[]

In [43]:
dates=driver.find_elements(By.XPATH,'//td[@class="column-2"]')
for i in dates[5:29]:
       date.append(i.text)
names=driver.find_elements(By.XPATH,'//td[@class="column-3"]')
for i in names[5:29]:
       name.append(i.text)
industrys=driver.find_elements(By.XPATH,'//td[@class="column-4"]')
for i in industrys[5:29]:
       industry.append(i.text)
subverticals=driver.find_elements(By.XPATH,'//td[@class="column-5"]')
for i in subverticals[5:29]:
       subvertical.append(i.text)
locations=driver.find_elements(By.XPATH,'//td[@class="column-6"]')
for i in locations[5:29]:
       location.append(i.text)
investors_names=driver.find_elements(By.XPATH,'//td[@class="column-7"]')
for i in investors_names[5:29]:
       investors_name.append(i.text)
investors_types=driver.find_elements(By.XPATH,'//td[@class="column-8"]')
for i in investors_types[5:29]:
       investors_type.append(i.text)
amounts=driver.find_elements(By.XPATH,'//td[@class="column-9"]')
for i in amounts[5:29]:
       amount.append(i.text)

In [44]:
df=pd.DataFrame({'Date':date,'Name':name,'Industry':industry,'Subvertical':subvertical,'Location':location,'Investors_name':investors_name,'Investors_type':investors_type,'Amount':amount})
df

Empty DataFrame
Columns: [Date, Name, Industry, Subvertical, Location, Investors_name, Investors_type, Amount]
Index: []

# Q7

7. Write a program to scrap all the available details of best gaming laptops from digit.in.

In [17]:
driver7=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# opening web page
driver7.get("https://digit.in")
driver7.maximize_window()
time.sleep(2)

In [18]:
top_10=driver7.find_element(By.XPATH,'//div[@class="menu"]//ul//li[4]')
top_10.click()

In [19]:
laptops=driver7.find_element(By.XPATH,"/html/body/div[4]/div/div/div[3]/div[2]/ul/li[22]/a")
laptops.click()

In [32]:
name = []
Price = []
OS = []
display = []
processor = []
weight = []
dimension = []



names=driver7.find_elements(By.XPATH,"//div[@class='right-container']/div/a/h3")
for i in names:
    name.append(i.text)

time.sleep(1)
#scraping operating system
os=driver7.find_elements(By.XPATH,"//div[@class='product-detail']/div/ul/li[1]/div/div")
for i in os:
    OS.append(i.text)

time.sleep(1)
#scraping display
displays=driver7.find_elements(By.XPATH,"//div[@class='product-detail']/div/ul/li[2]/div/div")
for i in displays:
    display.append(i.text)

time.sleep(1)
#scraping processor
processors=driver7.find_elements(By.XPATH,"//div[@class='product-detail']/div/ul/li[3]/div/div")
for i in processors:
    processor.append(i.text)


time.sleep(1)
# scraping weight
weights=driver7.find_elements(By.XPATH,"//div[@class='Spcs-details'][1]/table/tbody/tr[7]/td[3]")# extrat weight form xpath
for i in weights:
    weight.append(i.text)

time.sleep(1)
# scraping dimension
dimension=[]
dimensions=driver7.find_elements(By.XPATH,"//div[@class='Spcs-details'][1]/table/tbody/tr[8]/td[3]") 
for i in dimensions:
    dimension.append(i.text)

time.sleep(1)

#scraping price
price=driver7.find_elements(By.XPATH,"//table[@id='summtable']//tr//td[3]")
for i in price:
    Price.append(i.text)

In [33]:
print(len(name),len(Price),len(OS),len(display),len(weight),len(dimension),len(processor))

0 10 10 10 0 0 0

In [36]:
df=pd.DataFrame({'Price':Price,'os':OS,'display':display,})
df

       Price                os             display
0  ₹ 149,990  NA Playback Time  NA Frequency Range
1  ₹ 115,200  NA Playback Time  NA Frequency Range
2  ₹ 199,990  NA Playback Time  NA Frequency Range
3   ₹ 79,000  NA Playback Time  NA Frequency Range
4   ₹ 79,990  NA Playback Time  NA Frequency Range
5   ₹ 70,980  NA Playback Time  NA Frequency Range
6    ₹ 4,314  NA Playback Time  NA Frequency Range
7   ₹ 59,990  NA Playback Time  NA Frequency Range
8   ₹ 39,985  NA Playback Time  NA Frequency Range
9   ₹ 39,990  NA Playback Time  NA Frequency Range

# Q8

8. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [4]:
driver8=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# opening web page
driver8.get("https://www.forbes.com/billionaires/")
driver8.maximize_window()
time.sleep(2)

In [5]:
rank = []
name = []
net_worth = []
age = []
citzn = []
source = []
industry = []

#Fetching Rank
rank_tag = driver8.find_elements(By.XPATH,"//div[@class='rank']")
for r in rank_tag:
    try:
        rank.append(r.text)
    except NoSuchElementException:
        rank.append("-")
    
#Fetching Name
name_tag = driver8.find_elements(By.XPATH,"//div[@class='personName']")
for n in name_tag:
    try:
        name.append(n.text)
    except NoSuchElementException:
        name.append("-")
        
#Fetching Net Worth
netwrth_tag = driver8.find_elements(By.XPATH,"//div[@class='netWorth']")
for nt in netwrth_tag:
    try:
        net_worth.append(nt.text)
    except NoSuchElementException:
        net_worth.append("-")
        
#Fetching Age
age_tag = driver8.find_elements(By.XPATH,"//div[@class='age']")
for a in age_tag:
    try:
        age.append(a.text)
    except NoSuchElementException:
        age.append("-")
    
#Fetching Citizenship
cit_tag = driver8.find_elements(By.XPATH,"//div[@class='countryOfCitizenship']")
for c in cit_tag:
    try:
        citzn.append(c.text)
    except NoSuchElementException:
        citzn.append("-")
    
#Fetching Source
src_tag = driver8.find_elements(By.XPATH,"//span[@class='source-text']")
for s in src_tag:
    try:
        source.append(s.text)
    except NoSuchElementException:
        source.append("-")
    
#Fetching Industry
ind_tag = driver8.find_elements(By.XPATH,"//div[@class='category']")
for ind in ind_tag:
        try:
            industry.append(ind.text)
        except NoSuchElementException:
            industry.append("-")

In [6]:
len(rank),len(name),len(net_worth),len(age),len(citzn),len(source),len(industry)

(200, 200, 200, 200, 200, 200, 200)

In [7]:
billionaire =pd.DataFrame({'Rank':rank,'Name':name,'Net Worth':net_worth,'Age': age,'Citizenship/Country':citzn,'Source':source,'Industry':industry})
billionaire

,Rank,Name,Net Worth,Age,Citizenship/Country,Source,Industry
0,1.,Elon Musk,$219 B,50,United States,"Tesla, SpaceX",Automotive
1,2.,Jeff Bezos,$171 B,58,United States,Amazon,Technology
2,3.,Bernard Arnault & family,$158 B,73,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$129 B,66,United States,Microsoft,Technology
4,5.,Warren Buffett,$118 B,91,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...,...
195,192.,Marcel Herrmann Telles,$10.3 B,72,Brazil,beer,Food & Beverage
196,197.,Leon Black,$10 B,70,United States,private equity,Finance & Investments
197,197.,Joe Gebbia,$10 B,40,United States,Airbnb,Technology
198,197.,David Geffen,$10 B,79,United States,"movies, record labels",Media & Entertainment
199,197.,Yu Renrong,$10 B,56,China,semiconductors,Manufacturing

# Q9

9. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [12]:
driver9=webdriver.Chrome('chromedriver.exe')
driver9.get("https://www.youtube.com/watch?v=AETFvQonfV8")
driver9.maximize_window()
time.sleep(2)

In [13]:
for _ in range(500):
    driver9.execute_script("window.scrollBy(0,500)")

In [14]:
i=0
while(i<100):
    driver9.execute_script("window.scrollBy(0,500)") # scroll down to get more comments
    i+=1
while(i<402):
    driver9.execute_script("window.scrollBy(0,5000)") # scroll down to get more comments
    i+=1
    
comment = []
upvote = []
comment_time = []

comment_tag=(driver9.find_elements(By.XPATH,'//yt-formatted-string[@id="content-text"]'))
for i in comment_tag[0:501]:             
    try:
        comment.append(i.text)
    except NoSuchElementException:
        comment.append("-")

upvote_tag=(driver9.find_elements(By.XPATH,"//*[@id='vote-count-middle']"))
for i in upvote_tag[0:501]:             
    try:
        upvote.append(i.text)
    except NoSuchElementException:
        upvote.append("-")

comment_time_tag=(driver9.find_elements(By.XPATH,"//*[@id='header-author']/yt-formatted-string/a"))
for i in comment_time_tag[0:501]:             
    try:
        comment_time.append(i.text)
    except NoSuchElementException:
        comment_time.append("-")

In [15]:
len(comment),len(upvote),len(comment_time)

(60, 60, 60)

In [16]:
video=pd.DataFrame({"Comment":comment,"Upvote":upvote,"Comment_ Time":comment_time})
video

,Comment,Upvote,Comment_ Time
0,ॐ श्री गणेशाय नमः\nजय श्री राम जय हनुमान \nॐ न...,45,13 hours ago
1,When I listen this bhajan I feeling very much,28,7 days ago
2,Mind fresh song,10,10 days ago
3,Love so much hanuman ji,25,12 hours ago
4,Heart touching,38,21 hours ago
5,Jay hanuman ji️,18,13 hours ago
6,सुबह दिन की शुरुआत हनुमान चालीसा को सुनकर करे ...,54,21 hours ago
7,️ nice Feeling,9,6 days ago
8,Today 25 January I am watching this powerful m...,9,9 days ago
9,जय हनुमान,12,13 hours ago
10,बालाजी महाराज की जय हो हर हर महादेव ️,29,2 days ago
11,"""कवन सौ काज कठिन जग माही,\nजो नही होत तात तुम ...",38,13 hours ago
12,JAY SHREE RAM,60,3 days ago
13,When I listen this chalisha I very proud to be...,3,20 minutes ago
14,This bhajan next level mental peace .....jay s...,81,12 days ago
15,Jai Shree Ram Jai Hanuman,13,13 hours ago
16,When I am upset I heard and I feel good. Jai ...,8,3 days ago (edited)
17,प्रेम से बोलो राम भक्त हनुमान की जय।\nसिया वर ...,13,13 hours ago
18,Proud to be a HINDU,81,8 days ago
19,Whenever I buy a new sound system or sound rel...,5,7 days ago
20,"After reading this chalisa , I feel peaceful",53,14 hours ago
21,Jai shree krishna ️,8,19 hours ago
22,A next-level felling.,50,1 day ago
23,"हृदय में एक ऊर्जा प्रकट हुई,,, जय श्री राम दूत...",3,10 hours ago
24,श्री हनुमान चालीसा ️\nदोहा️\nश्रीगुरु चरन सरोज...,366,3 days ago
25,Hanuman ji was an Avatar of Lord Shiva.\nHar H...,70,11 days ago
26,Hanuman chalisa is like a energy booster for m...,362,11 days ago
27,3B ka kis kis ko wait hai \nBajrang Bali ki jay,22,18 hours ago
28,Today my ssc gd exam but this song give me a p...,15,3 days ago
29,ॐ हं हनुमते नमः।,7,13 hours ago
30,Hanuman chalisa is most beautiful,105,1 day ago
31,Having views more than a bollywood song \nJai ...,3,3 days ago
32,Whenever I am depressed I hear it and it gives...,188,11 days ago
33,जय श्री राम\nजय जय श्री हनुमान,3,13 hours ago
34,बालाजी महाराज की जय हर हर महादेव ️,48,14 hours ago
35,ॐ श्री हनुमंत शरणम् जय जय श्री राम ॐ श्री हनुम...,1,14 hours ago
36,जो भी बजरंगबली की यह मधुर हनुमान चालीसा सुन रह...,309,1 year ago
37,You're my everything my Lord Hanuman ji I'm n...,231,8 days ago
38,peacefull song......jai shree ram \njai hanuman,,2 hours ago
39,Heart touching,3,2 days ago
40,Jay Bajrangbali ️,3,11 hours ago
41,"प्रति क्षण कोई न कोई, बजरंगबली के इस सुप्रसिद्...",47,4 days ago
42,291 crore views on this video itself says how ...,52,4 days ago
43,I love hanuman chalisa,28,3 days ago
44,Jai hanuman ji,2,14 hours ago
45,Every morning everywhere jai shree Ram,2,8 days ago
46,ॐ श्री हनुमते नमः ||,2,12 hours ago
47,"My brother currently in different state, he lo...",132,8 days ago (edited)
48,जब जब भी मैं हनुमान चालीसा को सुनता हूं मेरे म...,72,4 days ago
49,Very soon 3B view's this is so proud moment fo...,15,5 days ago
50,जय श्री राम जय हनुमान,1,13 hours ago
51,M muslim but jab bhi m ye sunta hu ek alag hi ...,595,11 days ago
52,Jai shree ram jai hanuman,1,11 hours ago
53,Good song,2,4 days ago
54,Congratulations on 12 Million Likes on our Ha...,13,2 days ago (edited)
55,my favourite song chalisa jai shree shyam Siy...,1,3 hours ago
56,I listened at night everyday ️,25,9 days ago
57,Jai Sitaram jai hanuman ji i love this song,1,18 hours ago
58,जय हनुमान ज्ञान गुन सागर,48,1 day ago
59,"Tomorrow is my jee mains examination, and i ha...",224,5 days ago