In [51]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\nirma\anaconda3\lib\site-packages (4.7.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: trio~=0.17 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: sortedcontainers in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sniffio in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: outcome in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: pycparser in c:\users\nirma\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\nirma\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\nirma\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\nirma\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [20]:
import selenium 
import pandas as pd
from selenium import webdriver

import warnings 
warnings.filterwarnings('ignore')

from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException

from selenium.webdriver.common.by import By
import time

from PIL import Image
import io
import requests

# ---------------------------------------Q1-------------------------------------------------

1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [36]:
driver=webdriver.Chrome('chromedriver.exe')
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
driver.maximize_window()
time.sleep(5)

In [38]:
# find table containing the video details
table = driver.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/main/div[2]/div[3]/div[1]/table[2]')


#scraping the rank
rank =[]
try:
    Ranks=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in Ranks:
        rank.append(i.text)
except NoSuchElementException: #handling no such element exception
    rank.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    rank.append('No details available')
time.sleep(2) 



#scraping the names
name =[]
try:
    names=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException: #handling no such element exception
    name.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    name.append('No details available')
time.sleep(2) 




#scraping the artist
artist =[]
try:
    art=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in art:
        artist.append(i.text)
except NoSuchElementException: #handling no such element exception
    artist.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    artist.append('No details available')
time.sleep(2) 




#scraping the Upload date
Upload_date =[]
try:
    date=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in date:
        Upload_date.append(i.text)
except NoSuchElementException: #handling no such element exception
    Upload_date.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    Upload_date.append('No details available')
time.sleep(2)  




#scraping the views
views =[]
try:
    view=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in view:
        views.append(i.text)
except NoSuchElementException: #handling no such element exception
    views.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    views.append('No details available')
time.sleep(2)

In [39]:
# print the length
print(len(rank),len(name),len(artist),len(Upload_date),len(views))

30 30 30 30 30

In [40]:
import pandas as pd
df = pd.DataFrame({'RANK':rank,'NAME':name,'ARTIST':artist,'UPLOAD DATE':Upload_date,"VIEWS":views})
df

,RANK,NAME,ARTIST,UPLOAD DATE,VIEWS
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,12.27,"June 17, 2016"
1,2.,"""Despacito""[7]",Luis Fonsi,8.08,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,6.61,"October 8, 2016"
3,4.,"""Bath Song""[15]",Cocomelon – Nursery Rhymes,6.01,"May 2, 2018"
4,5.,"""Shape of You""[16]",Ed Sheeran,5.91,"January 30, 2017"
5,6.,"""See You Again""[18]",Wiz Khalifa,5.78,"April 6, 2015"
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,5.15,"March 6, 2014"
7,8.,"""Wheels on the Bus""[24]",Cocomelon – Nursery Rhymes,4.92,"May 24, 2018"
8,9.,"""Uptown Funk""[25]",Mark Ronson,4.83,"November 19, 2014"
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[26]",Miroshka TV,4.81,"February 27, 2018"
10,11.,"""Gangnam Style""[27]",Psy,4.69,"July 15, 2012"
11,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,4.53,"January 31, 2012"
12,13.,"""Dame Tu Cosita""[33]",El Chombo,4.23,"April 5, 2018"
13,14.,"""Sugar""[34]",Maroon 5,3.82,"January 14, 2015"
14,15.,"""Axel F""[35]",Crazy Frog,3.75,"June 16, 2009"
15,16.,"""Roar""[36]",Katy Perry,3.73,"September 5, 2013"
16,17.,"""Counting Stars""[37]",OneRepublic,3.72,"May 31, 2013"
17,18.,"""Sorry""[38]",Justin Bieber,3.63,"October 22, 2015"
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,3.55,"October 7, 2014"
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,3.49,"June 25, 2018"
20,21.,"""Waka Waka (This Time for Africa)""[41]",Shakira,3.47,"June 4, 2010"
21,22.,"""Dark Horse""[42]",Katy Perry,3.45,"February 20, 2014"
22,23.,"""Faded""[43]",Alan Walker,3.40,"December 3, 2015"
23,24.,"""Let Her Go""[44]",Passenger,3.38,"July 25, 2012"
24,25.,"""Girls Like You""[45]",Maroon 5,3.37,"May 31, 2018"
25,26.,"""Perfect""[46]",Ed Sheeran,3.37,"November 9, 2017"
26,27.,"""Bailando""[47]",Enrique Iglesias,3.33,"April 11, 2014"
27,28.,"""Lean On""[48]",Major Lazer,3.33,"March 22, 2015"
28,29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,3.30,"January 26, 2018"
29,30.,"""Lakdi Ki Kathi""[50]",Jingle Toons,3.30,"June 14, 2018"

# --------------------------------------Q2------------------------------------------

# 2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [27]:
from selenium import webdriver
driver2=webdriver.Chrome('chromedriver.exe')
driver2.get(" https://www.bcci.tv/.")
driver2.maximize_window()
time.sleep(5)

In [28]:
#click on internation fixture
international = driver2.find_element(By.XPATH,"//*[@id='navigation']/ul[1]/li[2]/a")
international.click()

In [29]:
#scraping match title   
match_title=[]
title=driver2.find_elements(By.XPATH,"//span[@class='matchOrderText ng-binding ng-scope']")
try:
    for i in title:
        match_title.append(i.text)

except NoSuchElementException: #handling no such element exception
    match_title.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    match_title.append('No details available')
time.sleep(2)



#scraping series name
series=[]
ser=driver2.find_elements(By.XPATH,"//span[@class='ng-binding']")
try:
    for i in ser:
        series.append(i.text)

except NoSuchElementException: #handling no such element exception
    series.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
     series.append('No details available')
time.sleep(2) 


#scraping place name 
place=[]
pla=driver2.find_elements(By.XPATH,"//span[@class='ng-binding ng-scope']")
try:
    for i in pla:
        place.append(i.text)

except NoSuchElementException: #handling no such element exception
    place.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
     place.append('No details available')
time.sleep(2) 

#scraping date

Date=[]
din=driver2.find_elements(By.XPATH,"//h5[@class='ng-binding']")
try:
    for i in din:
        Date.append(i.text)

except NoSuchElementException: #handling no such element exception
    Date.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
     Date.append('No details available')
time.sleep(2) 

#scraping match time

clock=[]
samay=driver2.find_elements(By.XPATH,"//h5[@class='text-right ng-binding']")
try:
    for i in samay:
        clock.append(i.text)

except NoSuchElementException: #handling no such element exception
    clock.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
     clock.append('No details available')
time.sleep(2)

In [30]:
import pandas as pd
df = pd.DataFrame({'MATCH TITLE':match_title,'SERIES NAME':series,'PLACE':place ,'DATE':Date,"TIME":clock})
df

,MATCH TITLE,SERIES NAME,PLACE,DATE,TIME
0,1st T20I -,ICC WOMENS T20 WORLD CUP 2023,"Newlands,",12 FEB 2023,6:30 PM IST
1,2nd T20I -,ICC WOMENS T20 WORLD CUP 2023,"Newlands,",15 FEB 2023,6:30 PM IST
2,2nd Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Arun Jaitley Stadium,",17 FEB 2023,9:30 AM IST
3,3rd T20I -,ICC WOMENS T20 WORLD CUP 2023,"St George's Park,",18 FEB 2023,6:30 PM IST
4,4th T20I -,ICC WOMENS T20 WORLD CUP 2023,"St George's Park,",20 FEB 2023,6:30 PM IST
5,3rd Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Himachal Pradesh Cricket Association Stadium,",1 MAR 2023,9:30 AM IST
6,4th Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Narendra Modi Stadium,",9 MAR 2023,9:30 AM IST
7,1st ODI -,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,"Wankhede Stadium,",17 MAR 2023,1:30 PM IST

# ------------------------------------------Q3-----------------------------------------

3. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [58]:
from selenium import webdriver
driver3=webdriver.Chrome('chromedriver.exe')
driver3.get("  http://statisticstimes.com/")
driver3.maximize_window()
time.sleep(5)

In [59]:
economy = driver3.find_element(By.XPATH,"//*[@id='top']/div[2]/div[2]/button")
economy.click()
time.sleep(5)

In [60]:
india = driver3.find_element(By.XPATH,"//*[@id='top']/div[2]/div[2]/div/a[3]")
india.click()
time.sleep(5)

In [61]:
gdp = driver3.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
gdp.click()
time.sleep(5)

In [62]:
#scraping the rank
rank =[]
try:
    Ranks=driver3.find_elements(By.XPATH,"//td[@class='data1']")
    for i in Ranks[:33]:
        rank.append(i.text)
except NoSuchElementException: #handling no such element exception
    rank.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    rank.append('No details available')
time.sleep(2) 

#scraping state names
state=[]
try:
    unit = driver3.find_elements(By.XPATH,"//td[@class='name'] ")
    for i in unit[:33]:
        state.append(i.text)
except NoSuchElementException: 
    state.append("-")
except StaleElementReferenceException:
    state.apppend("-")
time.sleep(2)

#scraping  GSDP(18-19)- at current prices

GSDP_18_19 =[]
try:
    gsdp = driver3.find_elements(By.XPATH,"//td[@class='data sorting_1'] ")
    for i in gsdp[:33]:
        GSDP_18_19.append(i.text)
except NoSuchElementException: 
    GSDP_18_19.append("-")
except StaleElementReferenceException:
    GSDP_18_19.apppend("-")
time.sleep(2)

#scraping  GSDP(18-19)- at current prices

GSDP_19_20 =[]
try:
    DP_19_20 = driver3.find_elements(By.XPATH,"//td[@class='data'][1]  ")
    for i in DP_19_20[:33]:
        GSDP_19_20.append(i.text)
except NoSuchElementException: 
    GSDP_19_20.append("-")
except StaleElementReferenceException:
    GSDP_19_20.apppend("-")
time.sleep(2)

#scraping share(18-19)
share_18_19=[]
try:
    share = driver3.find_elements(By.XPATH," //td[@class='data'][2]")
    for i in share[:33]:
        share_18_19.append(i.text)
except NoSuchElementException: 
    share_18_19.append("-")
except StaleElementReferenceException:
    share_18_19.apppend("-")
time.sleep(2)

#scraping GDP($ billion)
GDP=[]
try:
    billion = driver3.find_elements(By.XPATH," //td[@class='data'][3]")
    for i in billion[:33]:
        GDP.append(i.text)
except NoSuchElementException: 
    GDP.append("-")
except StaleElementReferenceException:
    GDP.apppend("-")
time.sleep(2)

In [63]:
import pandas as pd
df = pd.DataFrame({'RANK':rank,'STATE':state,'GSDP(18-19)- at current prices':GSDP_18_19 ,'GSDP(19-20)- at current prices':GSDP_19_20,
                   "Share(18-19)":share_18_19,"GDP($ billion)":GDP })
df

,RANK,STATE,GSDP(18-19)- at current prices,GSDP(19-20)- at current prices,Share(18-19),GDP($ billion)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# --------------------------------------------Q4------------------------------------

4. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [13]:
from selenium import webdriver
driver4=webdriver.Chrome('chromedriver.exe')
driver4.get(" https://github.com/")
driver4.maximize_window()
time.sleep(5)

In [14]:
#click on explore button
Explore = driver4.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button")
Explore.click()

In [15]:
#Select trending option
trending = driver4.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a")
trending.click()

In [16]:
#creating empty list
repo_urls = []  
rep_title = []
Description =[]
Contributors=[]
Language=[]

In [17]:
#Scraping urls for each repository
repository = driver4.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']//a")
for i in repository[0:30]:
    repo_urls.append(i.get_attribute("href"))

    
#Scraping data from every repository page
for i in repo_urls:
    driver4.get(i)
    time.sleep(3)
    
    #Scraping description-
    try:
        title = driver4.find_element(By.XPATH,'//div[@class=" d-flex flex-wrap flex-items-center wb-break-word f3 text-normal"]')
        rep_title.append(title.text)
    except NoSuchElementException:
        rep_title.append('-')  
    
    #Scraping description-
    try:
        desc = driver4.find_element(By.XPATH,'//p[@class="f4 my-3"]')
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    #Scraping contributors count-
    try:
        cont_tags = driver4.find_element(By.XPATH,"//*[contains(text(),'    Contributors ')]")
        Contributors.append(cont_tags.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
        
        
    #Scraping Languages-
    try:
        cont_tags = driver4.find_element(By.XPATH,'//span[@class="color-fg-default text-bold mr-1"]')
        Language.append(cont_tags.text)
    except NoSuchElementException:
        Language.append('-')

In [18]:
#print the length of column 
print(len(rep_title),len(Description),len(Contributors),len(Language))

25 25 25 25

In [19]:
import pandas as pd
df = pd.DataFrame({'Repository title':rep_title,'Repository description':Description,
                   'Contributors count':Contributors,'Language used':Language})
df

,Repository title,Repository description,Contributors count,Language used
0,acikkaynak\n/\ndeprem-yardim-backend-go\nPublic,-,16,Go
1,cloudflare\n/\nwildebeest\nPublic,Wildebeest is an ActivityPub and Mastodon-comp...,12,TypeScript
2,jaymody\n/\npicoGPT\nPublic,An unnecessarily tiny and minimal implementati...,2,Python
3,eliaszon\n/\nProgrammers-Overseas-Job-Intervie...,🏂🏻 程序员海外工作/英文面试手册,-,-
4,uutils\n/\ncoreutils\nPublic,Cross-platform Rust rewrite of the GNU coreutils,351,Rust
5,rustdesk\n/\nrustdesk\nPublic,Open source virtual / remote desktop infrastru...,156,Rust
6,MichalGeyer\n/\nplug-and-play\nPublic,Official Pytorch Implementation for “Plug-and-...,2,Python
7,pedroslopez\n/\nwhatsapp-web.js\nPublic,A WhatsApp client library for NodeJS that conn...,84,JavaScript
8,djun\n/\nwechatbot\nPublic,为个人微信接入ChatGPT,-,Go
9,fuergaosi233\n/\nwechat-chatgpt\nPublic,Use ChatGPT On Wechat via wechaty,25,TypeScript
10,TheD1rkMtr\n/\nFilelessPELoader\nPublic,"Loading Remote AES Encrypted PE in memory , De...",-,C++
11,eryajf\n/\nchatgpt-dingtalk\nPublic,ChatGPT机器人在钉钉群聊中交互,-,Go
12,aquasecurity\n/\ntrivy\nPublic,"Find vulnerabilities, misconfigurations, secre...",279,Go
13,ethereum-optimism\n/\nop-analytics\nPublic,"On-Chain Data, Utilities, References, and othe...",-,-
14,nerfstudio-project\n/\nnerfstudio\nPublic,A collaboration friendly studio for NeRFs,75,Python
15,AIGCT\n/\nEASYChatGPT\nPublic,"This is an application project of 'chatgpt',on...",-,Python
16,leminlimez\n/\nCowabunga\nPublic,iOS 14.0-15.7.1 & 16.0-16.1.2 MacDirtyCow ToolBox,6,Swift
17,PlexPt\n/\nchatgpt-java\nPublic,ChatGPT Java SDK. Lightweight package for inte...,-,Java
18,Shopify\n/\nhydrogen\nPublic,Hydrogen is Shopify’s stack for headless comme...,20,TypeScript
19,Fndroid\n/\nclash_for_windows_pkg\nPublic,A Windows/macOS GUI based on Clash,3,-
20,f\n/\nawesome-chatgpt-prompts\nPublic,This repo includes ChatGPT prompt curation to ...,59,HTML
21,enhuiz\n/\nvall-e\nPublic,An unofficial PyTorch implementation of the au...,-,Python
22,zhayujie\n/\nchatgpt-on-wechat\nPublic,使用ChatGPT搭建微信聊天机器人，基于OpenAI API和itchat实现。Wecha...,7,Python
23,Leizhenpeng\n/\nfeishu-chatGpt\nPublic,Feishu ChatGpt 在飞书上与ChatGPT随时对话~,3,Go
24,activepieces\n/\nactivepieces\nPublic,No-code Business Automation Tool. An open sour...,18,TypeScript

# --------------------------------------Q5------------------------------------------

5. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [21]:
from selenium import webdriver
driver5=webdriver.Chrome('chromedriver.exe')
driver5.get(" https:/www.billboard.com/")
driver5.maximize_window()
time.sleep(5)

In [22]:
# Click on chart
charts = driver5.find_element(By.XPATH,"/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a")
charts.click()

In [23]:
#click on billboard_100songs
billboard_100songs = driver5.find_element(By.XPATH,"/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a")
billboard_100songs.click()

In [24]:
#scraping the 100 songs with details

#scraping the song name 
song_name=[]
try:
    name = driver5.find_elements(By.XPATH,"//div[@class='o-chart-results-list-row-container']//ul/li//h3")
    for i in name:
        song_name.append(i.text)
except NoSuchElementException:  #handling no such element exception
    song_name.append("-")
except StaleElementReferenceException: #handling Stale element exception
    song_name.append("-")
time.sleep(2) 


#scraping the artist
artist =[]
try:
    art=driver5.find_elements(By.XPATH,"//li[@class='lrv-u-width-100p']//ul//li[1]//span")
    for i in art:
        artist.append(i.text)
except NoSuchElementException: #handling no such element exception
    artist.append("-")
except StaleElementReferenceException: #handling Stale element exception
    artist.append("-")
time.sleep(2) 

#scraping the Last week rank
last_week_rank =[]
try:
    rank=driver5.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max'][1]//span[1]")
    for i in rank:
        last_week_rank.append(i.text)
except NoSuchElementException: #handling no such element exception
    last_week_rank.append("-")
except StaleElementReferenceException: #handling Stale element exception
    last_week_rank.append("-")
time.sleep(2) 

#scraping the peak rank
peak_rank =[]
try:
    p_rank=driver5.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max'][2]")
    for i in p_rank:
        peak_rank.append(i.text)
except NoSuchElementException: #handling no such element exception
    peak_rank.append("-")
except StaleElementReferenceException: #handling Stale element exception
    peak_rank.append("-")
time.sleep(2)

#scraping the Weeks on board
Weeks_board=[]
try:
    board=driver5.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max'][2]//span[1]")
    for i in rank:
        Weeks_board.append(i.text)
except NoSuchElementException: #handling no such element exception
    Weeks_board.append("-")
except StaleElementReferenceException: #handling Stale element exception
    Weeks_board.append("-")
time.sleep(2)

In [25]:
#print the length of each column  
print(len(song_name),len(artist),len(last_week_rank),len(Weeks_board),len(peak_rank))

100 100 100 100 100

In [26]:
import pandas as pd
df = pd.DataFrame({'SONG NAME':song_name,'ARTIST':artist,'LAST WEEK RANK':last_week_rank ,'PEAK RANK':peak_rank,"WEEK BOARD":Weeks_board})
df

,SONG NAME,ARTIST,LAST WEEK RANK,PEAK RANK,WEEK BOARD
0,Flowers,Miley Cyrus,1,1,1
1,Kill Bill,SZA,2,2,2
2,Creepin',"Metro Boomin, The Weeknd & 21 Savage",4,3,4
3,Anti-Hero,Taylor Swift,3,1,3
4,Unholy,Sam Smith & Kim Petras,5,1,5
...,...,...,...,...,...
95,Hey Mor,Ozuna Featuring Feid,-,96,-
96,Gato de Noche,Nengo Flow & Bad Bunny,85,60,85
97,Heart To Heart,Mac DeMarco,83,83,83
98,Never Gonna Not Dance Again,P!nk,-,99,-
99,Dancin' In The Country,Tyler Hubbard,-,100,-

# ----------------------------------------Q6---------------------------------------

6. Scrape the details of Highest sellingnovels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [53]:
from selenium import webdriver
driver6=webdriver.Chrome('chromedriver.exe')
driver6.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")
driver6.maximize_window()
time.sleep(5)

In [55]:
#scraping the Book names
name =[]
try:
    names=driver6.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException: #handling no such element exception
    name.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    name.append('No details available')
    time.sleep(2) 

#scraping the Author names
author_name =[]
try:
    author=driver6.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in author:
        author_name.append(i.text)
except NoSuchElementException: #handling no such element exception
    author_name.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    author_name.append('No details available')
    time.sleep(2) 

#scraping the Volumes sold
volume_sold= []
try:
    sold=driver6.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in  sold[:100]:
        volume_sold.append(i.text)
except NoSuchElementException: #handling no such element exception
    volume_sold.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    volume_sold.append('No details available')
    time.sleep(2) 

#scraping the publisher
publisher= []
try:
    pub=driver6.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in  pub[:100]:
        publisher.append(i.text)
except NoSuchElementException: #handling no such element exception
    publisher.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    publisher.append('No details available')
    time.sleep(2) 

#scraping the genre
Genre = []
try:
    genre=driver6.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in  genre[:100]:
        Genre.append(i.text)
except NoSuchElementException: #handling no such element exception
    Genre.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    Genre.append('No details available')
    time.sleep(2)

In [56]:
# print the length
print(len(name),len(author_name),len(volume_sold ),len(publisher),len(Genre))

100 100 100 100 100

In [57]:
import pandas as pd
df = pd.DataFrame({'BOOK NAME':name,'AUTHOR NAME':author_name,'VOLUME SOLD':volume_sold ,'PUBLISHER':publisher,"GENRE":Genre})
df

,BOOK NAME,AUTHOR NAME,VOLUME SOLD,PUBLISHER,GENRE
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# ----------------------------------------Q7--------------------------------------

7. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [44]:
from selenium import webdriver
driver7=webdriver.Chrome('chromedriver.exe')
driver7.get("https://www.imdb.com/list/ls095964455/")
driver7.maximize_window()
time.sleep(5)

In [45]:
#scraping the names
name =[]
try:
    names=driver7.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a")
    for i in names[:100]:
        name.append(i.text)
except NoSuchElementException: #handling no such element exception
    name.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    name.append('No details available')
    time.sleep(2) 

#scraping the year
Year_span = []
try:
    Year=driver7.find_elements(By.XPATH,"//h3[@class='lister-item-header']/span[2]")
    for i in  Year[:100]:
        Year_span.append(i.text)
except NoSuchElementException: #handling no such element exception
    Year_span.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    Year_span.append('No details available')
    time.sleep(2) 

#scraping the genre
Genre = []
try:
    genre=driver7.find_elements(By.XPATH,"//span[@class='genre']")
    for i in  genre[:100]:
        Genre.append(i.text)
except NoSuchElementException: #handling no such element exception
    Genre.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    Genre.append('No details available')
    time.sleep(2) 

#scraping the run time
run_time = []
try:
    time=driver7.find_elements(By.XPATH,"//span[@class='runtime']")
    for i in time[:100]:
        run_time.append(i.text)
except NoSuchElementException: #handling no such element exception
    run_time.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    run_time.append('No details available')
    time.sleep(2) 
    
#scraping the rating
rating = []
try:
    rate=driver7.find_elements(By.XPATH,"//span[@class='runtime']")
    for i in rate[:100]:
        rating.append(i.text)
except NoSuchElementException: #handling no such element exception
    rating.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    rating.append('No details available')
    time.sleep(2) 
    
#scraping the votes
votes= []
try:
    Vote=driver7.find_elements(By.XPATH,"//p[@class='text-muted text-small'][3]/span[2]")
    for i in Vote[:100]:
        votes.append(i.text)
except NoSuchElementException: #handling no such element exception
    votes.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    votes.append('No details available')
    time.sleep(2)

In [46]:
# print the length
print(len(name),len(Year_span),len(Genre ),len(run_time),len(rating),len(votes))

100 100 100 100 100 100

In [47]:
import pandas as pd
df = pd.DataFrame({'NAME':name,'YEAR':Year_span,'GENRE':Genre ,'RUN TIME':run_time,"RATING":rating,"VOTES":votes})
df

,NAME,YEAR,GENRE,RUN TIME,RATING,VOTES
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,57 min,"2,122,085"
1,Stranger Things,(2016–2024),"Drama, Fantasy, Horror",51 min,51 min,"1,210,206"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,44 min,"1,006,415"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,60 min,"296,977"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,43 min,"255,917"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,42 min,"50,713"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,50 min,"62,590"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,42 min,"202,745"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,45 min,"42,038"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,572 min,"250,589"

# ----------------------------Q8--------------------------------------------------------------

# 8. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [31]:
from selenium import webdriver
driver8=webdriver.Chrome('chromedriver.exe')
driver8.get("https://archive.ics.uci.edu/")
driver8.maximize_window()
time.sleep(5)

In [32]:
#click on viewdataset link
view_dataset=driver8.find_element(By.XPATH,"//span[@class='whitetext']/a/font/b")
view_dataset.click()

In [33]:
#scraping the dataset names
dataset_name =[]
try:
    names=driver8.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]")
    for i in names:
        dataset_name.append(i.text)
except NoSuchElementException: #handling no such element exception
    dataset_name.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    dataset_name.append('No details available')
    time.sleep(2)
    
#scraping the Data type
data_type =[]
try:
    data=driver8.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in data:
        data_type.append(i.text)
except NoSuchElementException: #handling no such element exception
    data_type.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    data_type.append('No details available')
    time.sleep(2)
    
#scraping the task
task=[]
try:
    for i in driver8.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr//td[3]"):
        task.append(i.text)
except NoSuchElementException: #handling no such element exception
    task.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    taskappend('No details available')
    time.sleep(2)
    
#scraping the Attribute type
Attribute=[]
try:
    for i in driver8.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr//td[4]"):
        Attribute.append(i.text)
except NoSuchElementException: #handling no such element exception
    Attribute.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    Attribute.append('No details available')
    time.sleep(2)
    
    
#scraping the No of instances
instances=[]
try:
    for i in driver8.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr//td[5]"):
        instances.append(i.text)
except NoSuchElementException: #handling no such element exception
    instances.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    instances.append('No details available')
    time.sleep(2)
   
    
    
    
#scraping the  No of attribute
attribute=[]
try:
    for i in driver8.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr//td[6]"):
        attribute.append(i.text)
except NoSuchElementException: #handling no such element exception
    attribute.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    attribute.append('No details available')
    time.sleep(2)


#scraping the YEAR
year=[]
try:
    YEAR =driver8.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr//td[7]")
    for i in YEAR:
        year.append(i.text)
except NoSuchElementException: #handling no such element exception
    year.append('No details available')
except StaleElementReferenceException: #handling Stale element exception
    year.append('No details available')
    time.sleep(2)

In [36]:
import pandas as pd
df = pd.DataFrame({'NAME':dataset_name,'YEAR':data_type ,'GENRE':task ,'RUN TIME':Attribute,
                   "RATING":instances,"VOTES":attribute,"VOTES":year})
df.drop([0], inplace = True)
df

,NAME,YEAR,GENRE,RUN TIME,RATING,VOTES
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,1998
5,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,1998
...,...,...,...,...,...,...
618,Influenza outbreak event prediction via Twit...,Multivariate,Classification,"Integer, Real",75840,2020
619,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,2020
620,Maternal Health Risk Data Set,,Classification,,1014,2020
621,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,2021
622,Image Recognition Task Execution Times in Mo...,Univariate,Regression,Real,4000,2021