In [79]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\users\nirma\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\nirma\anaconda3\lib\site-packages (from bs4) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\nirma\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.3.1)
Requirement already satisfied: requests in c:\users\nirma\anaconda3\lib\site-packages (2.27.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\nirma\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\nirma\anaconda3\lib\site-packages (from requests) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nirma\anaconda3\lib\site-packages (from requests) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nirma\anaconda3\lib\site-packages (from requests) (2021.10.8)

In [114]:
import  requests
from  bs4 import BeautifulSoup
import warnings
warnings.filterwarnings("ignore")

# 1)Write a python program to display all the header tags from wikipedia.org.

In [3]:
url = requests.get('https://en.wikipedia.org/wiki/Main_Page')

In [4]:
soup = BeautifulSoup(url.content)

In [5]:
header =[]
for i in soup.find_all('span',class_="mw-headline"):
  header.append(i.text)
print(*header,sep='\n\n')

Welcome to Wikipedia

From today's featured article

Did you know ...

In the news

On this day

Today's featured picture

Other areas of Wikipedia

Wikipedia's sister projects

Wikipedia languages

# 2)Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release) and make data frame

In [126]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
#to collect the english translation of datas
headers={'Accept-Language':'en-US,en;q=0.5'}
#data of 50 movies in each page,hence each request fetches 50 movies data making it a total of 100 movies.
request=requests.get('https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc',headers=headers)
request1=requests.get('https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc&start=51&ref_=adv_nxt',headers=headers)
Soup=BeautifulSoup(request.content)
Soup1=BeautifulSoup(request1.content)
#append data of both Soup and Soup1
Soup.append(Soup1)
MoviesName=[]
Year=[]
Rating=[]
movies=Soup.find_all("div",class_='lister-item mode-advanced')
for m in movies:
    name=m.h3.a.text
    year=m.h3.find('span',class_='lister-item-year text-muted unbold').text
    rate=m.strong.text
    MoviesName.append(name)
    Year.append(year)
    Rating.append(rate)
Movies=pd.DataFrame({'Movie':MoviesName,'Year of Release':Year,'Rating':Rating},index=range(1,101))
Movies

                                             Movie Year of Release Rating
1                         The Shawshank Redemption          (1994)    9.3
2                                    The Godfather          (1972)    9.2
3                                  The Dark Knight          (2008)    9.0
4    The Lord of the Rings: The Return of the King          (2003)    9.0
5                           The Godfather: Part II          (1974)    9.0
..                                             ...             ...    ...
96                                         Vertigo          (1958)    8.3
97                              Lawrence of Arabia          (1962)    8.3
98                                    Citizen Kane          (1941)    8.3
99                                     Toy Story 3          (2010)    8.3
100                                              M          (1931)    8.3

[100 rows x 3 columns]

# 3) Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. name, rating, year of release) and make data frame.

In [125]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
req=requests.get('https://www.imdb.com/india/top-rated-indian-movies/')
Soup=BeautifulSoup(req.content)
movs=Soup.find_all('td',class_='titleColumn')
movs100=movs[0:100]
Mname=[]
Year=[]
for m in movs100:
    name=m.a.text
    year=m.span.text
    Mname.append(name)
    Year.append(year)
rate=Soup.find_all('td',class_='ratingColumn imdbRating')
rate100=rate[0:100]
IMDB=[]
for r in rate100:
    imdb=r.strong.text
    IMDB.append(imdb)
INDTOP=pd.DataFrame({'Name':Mname,'Year of Release':Year,'Rating':IMDB},index=range(1,101))
INDTOP

                                    Name Year of Release Rating
1    Ramayana: The Legend of Prince Rama          (1993)    8.5
2             Rocketry: The Nambi Effect          (2022)    8.4
3                                Golmaal          (1979)    8.4
4                                Nayakan          (1987)    8.4
5                             Anbe Sivam          (2003)    8.4
..                                   ...             ...    ...
96                           Jigarthanda          (2014)    8.0
97                        Kaakkaa Muttai          (2014)    8.0
98                               Kantara          (2022)    8.0
99                           Ustad Hotel          (2012)    8.0
100             Theeran Adhigaaram Ondru          (2017)    8.0

[100 rows x 3 columns]

# 4) Write s python program to display list of respected former presidents of India(i.e. Name , Term of office) from https://presidentofindia.nic.in/former-presidents.htm

In [10]:
url = requests.get('https://presidentofindia.nic.in/former-presidents.htm')

In [11]:
soup = BeautifulSoup(url.content)

In [12]:
president_name=[]
for i in soup.find_all('h3'):
    president_name.append(i.text)
president_name

['Shri Ram Nath Kovind (birth - 1945)',
 'Shri Pranab Mukherjee (1935-2020)',
 'Smt Pratibha Devisingh Patil (birth - 1934)',
 'DR. A.P.J. Abdul Kalam (1931-2015)',
 'Shri K. R. Narayanan (1920 - 2005)',
 'Dr Shankar Dayal Sharma (1918-1999)',
 'Shri R Venkataraman (1910-2009)',
 'Giani Zail Singh (1916-1994)',
 'Shri Neelam Sanjiva Reddy (1913-1996)',
 'Dr. Fakhruddin Ali Ahmed (1905-1977)',
 'Shri Varahagiri Venkata Giri (1894-1980)',
 'Dr. Zakir Husain (1897-1969)',
 'Dr. Sarvepalli Radhakrishnan (1888-1975)',
 'Dr. Rajendra Prasad (1884-1963) ']

In [13]:
term=[]
for i in soup.find_all('span',class_="terms"):
    term.append(i.text)
term

['Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:',
 'Term of Office:']

In [16]:
Detail=[]
for i in soup.find_all('div', class_="presidentListing"):
    Detail.append(i.text)
Detail

['\nShri Ram Nath Kovind (birth - 1945)\nTerm of Office: 25 July, 2017 to 25 July, 2022 \nhttps://ramnathkovind.nic.in\n',
 '\nShri Pranab Mukherjee (1935-2020)\nTerm of Office: 25 July, 2012 to 25 July, 2017 \nhttp://pranabmukherjee.nic.in\n',
 '\nSmt Pratibha Devisingh Patil (birth - 1934)\nTerm of Office: 25 July, 2007 to 25 July, 2012 \nhttp://pratibhapatil.nic.in\n',
 '\nDR. A.P.J. Abdul Kalam (1931-2015)\nTerm of Office: 25 July, 2002 to 25 July, 2007 \nhttp://abdulkalam.nic.in\n',
 '\nShri K. R. Narayanan (1920 - 2005)\nTerm of Office: 25 July, 1997 to 25 July, 2002 \n',
 '\nDr Shankar Dayal Sharma (1918-1999)\nTerm of Office: 25 July, 1992 to 25 July, 1997 \n',
 '\nShri R Venkataraman (1910-2009)\nTerm of Office: 25 July, 1987 to 25 July, 1992 \n',
 '\nGiani Zail Singh (1916-1994)\nTerm of Office: 25 July, 1982 to 25 July, 1987 \n',
 '\nShri Neelam Sanjiva Reddy (1913-1996)\nTerm of Office: 25 July, 1977 to 25 July, 1982 \n',
 '\nDr. Fakhruddin Ali Ahmed (1905-1977)\nTerm of Office: 24 August, 1974 to 11 February, 1977\n',
 '\nShri Varahagiri Venkata Giri (1894-1980)\nTerm of Office: 3 May, 1969 to 20 July, 1969 and 24 August, 1969 to 24 August, 1974\n',
 '\nDr. Zakir Husain (1897-1969)\nTerm of Office: 13 May, 1967 to 3 May, 1969\n',
 '\nDr. Sarvepalli Radhakrishnan (1888-1975)\nTerm of Office: 13 May, 1962 to 13 May, 1967\n',
 '\nDr. Rajendra Prasad (1884-1963) \nTerm of Office: 26 January, 1950 to 13 May, 1962\n']

In [17]:
import pandas as pd
df=pd.DataFrame({"PresidentiaL List":Detail})
df

                                    PresidentiaL List
0   \nShri Ram Nath Kovind (birth - 1945)\nTerm of...
1   \nShri Pranab Mukherjee (1935-2020)\nTerm of O...
2   \nSmt Pratibha Devisingh Patil (birth - 1934)\...
3   \nDR. A.P.J. Abdul Kalam (1931-2015)\nTerm of ...
4   \nShri K. R. Narayanan (1920 - 2005)\nTerm of ...
5   \nDr Shankar Dayal Sharma (1918-1999)\nTerm of...
6   \nShri R Venkataraman (1910-2009)\nTerm of Off...
7   \nGiani Zail Singh (1916-1994)\nTerm of Office...
8   \nShri Neelam Sanjiva Reddy (1913-1996)\nTerm ...
9   \nDr. Fakhruddin Ali Ahmed (1905-1977)\nTerm o...
10  \nShri Varahagiri Venkata Giri (1894-1980)\nTe...
11  \nDr. Zakir Husain (1897-1969)\nTerm of Office...
12  \nDr. Sarvepalli Radhakrishnan (1888-1975)\nTe...
13  \nDr. Rajendra Prasad (1884-1963) \nTerm of Of...

# 5) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:


c) Top 10 ODI bowlers along with the records of their team and rating.

a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.

In [119]:
page = requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')

In [120]:
soup = BeautifulSoup(page.content)

In [122]:
team = []
for i in soup.find_all('span',class_="u-hide-phablet"):
    team.append(i.text.replace('\n',"").strip())
team[:10]

['New Zealand',
 'England',
 'Australia',
 'India',
 'Pakistan',
 'South Africa',
 'Bangladesh',
 'Sri Lanka',
 'Afghanistan',
 'West Indies']

In [108]:
matches= []
for i in soup.find_all('td',class_="table-body__cell u-center-text"):
    matches.append(i.text)
matches[0:10]

['30', '3,400', '32', '3,572', '41', '4,515', '25', '2,649', '24', '2,392']

In [105]:
ratings= []
for i in soup.find_all('td',class_="table-body__cell u-text-right rating"):
    ratings.append(i.text)
ratings[:10]

['113', '112', '110', '106', '100', '95', '88', '71', '71', '53']

In [123]:
print(len(team),len(matches),len(ratings))

20 38 19

In [94]:
import pandas as pd

cf = pd.DataFrame({'Team':team,'Matches':matches,'Rating':rating})
cf

ValueError: All arrays must be of the same length

b) Top 10 ODI Batsmen along with the records of their team and rating

In [110]:
page = requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi')

In [111]:
soup = BeautifulSoup(page.content)

In [117]:
names = []
for i in soup.find_all('td',class_="table-body__cell name"):
    names.append(i.text)
names[0:10]

['\nRassie van der Dussen\n',
 '\nImam-ul-Haq\n',
 '\nQuinton de Kock\n',
 '\nDavid Warner\n',
 '\nVirat Kohli\n',
 '\nSteve Smith\n',
 '\nRohit Sharma\n',
 '\nJonny Bairstow\n',
 '\nFakhar Zaman\n',
 '\nJosh Hazlewood\n']

In [113]:
print(len(names))

54

# 7) Write a python program to scrape mentioned news details from https://www.cnbc.com/world/?region=world :

i) Headline
ii) Time
iii) News Link

In [18]:
page = requests.get('https://www.cnbc.com/world/?region=world')

In [19]:
soup = BeautifulSoup(page.content)

In [20]:
headline= []
for i in soup.find_all('a',class_="LatestNews-headline"):
    headline.append(i.text)

In [21]:
time= []
for i in soup.find_all('time',class_="LatestNews-timestamp"):
    time.append(i.text)

In [22]:
News_Link= []
for i in soup.find_all('a',class_="LatestNews-headline"):
    News_Link.append(i.get('href'))

In [93]:
import pandas as pd

nf = pd.DataFrame({'headline':headline,'Time':time,'News Link':News_Link})
nf

,headline,Time,News Link
0,Wall Street's favorite retail stocks include A...,31 Min Ago,https://www.cnbc.com/2023/01/15/wall-streets-f...
1,A busy movie calendar will lead to a 15% jump ...,34 Min Ago,https://www.cnbc.com/2023/01/15/a-busier-movie...
2,These tactical trades are among Goldman's favo...,35 Min Ago,https://www.cnbc.com/2023/01/15/these-tactical...
3,More classified documents found at Biden’s Del...,20 Hours Ago,https://www.cnbc.com/2023/01/14/white-house-sa...
4,The biggest risks of using Bluetooth trackers ...,20 Hours Ago,https://www.cnbc.com/2023/01/14/the-biggest-se...
5,Veganuary: 3 ways to meet your protein goals o...,22 Hours Ago,https://www.cnbc.com/2023/01/14/veganuary-3-wa...
6,Investing in last year's top 10 stocks is 'a r...,22 Hours Ago,https://www.cnbc.com/2023/01/14/best-performin...
7,4 side hustles for introverts: Some can bring ...,22 Hours Ago,https://www.cnbc.com/2023/01/14/side-hustles-f...
8,Here are the odds you'll win the $404 million ...,23 Hours Ago,https://www.cnbc.com/2023/01/14/powerball-odds...
9,The condo king of Miami is betting big on a ne...,23 Hours Ago,https://www.cnbc.com/2023/01/14/condo-king-mia...
10,Carmakers upgrade lineups to meet high-end dem...,23 Hours Ago,https://www.cnbc.com/2023/01/14/carmakers-upgr...
11,What it’s like to deliver for Amazon in new el...,23 Hours Ago,https://www.cnbc.com/2023/01/14/what-its-like-...
12,The bold bullish case to be made for U.S. stocks,24 Hours Ago,https://www.cnbc.com/2023/01/14/the-bold-bulli...
13,Earnings stars: Stocks expected to post the bi...,24 Hours Ago,https://www.cnbc.com/2023/01/14/earnings-stars...
14,Morgan Stanley says these are the most underva...,24 Hours Ago,https://www.cnbc.com/2023/01/14/stocks-like-di...
15,"Stocks on a roll. But overbought market, earni...",24 Hours Ago,https://www.cnbc.com/2023/01/14/investing-club...
16,The zero-fare public transit movement is picki...,24 Hours Ago,https://www.cnbc.com/2023/01/14/zero-fare-publ...
17,"Building self-discipline by age 27 is crucial,...",24 Hours Ago,https://www.cnbc.com/2023/01/14/psychiatrist-f...
18,Iran executes British-Iranian national despite...,"January 14, 2023",https://www.cnbc.com/2023/01/14/iran-executes-...
19,Rising commodities prices could be a tailwind ...,"January 13, 2023",https://www.cnbc.com/2023/01/13/rising-commodi...
20,Cramer's lightning round: Costamare is not a buy,"January 13, 2023",https://www.cnbc.com/2023/01/13/cramers-lightn...
21,Cramer’s week ahead: Wait before trading on co...,"January 13, 2023",https://www.cnbc.com/2023/01/13/cramers-week-a...
22,CDC review finds it’s unlikely Pfizer booster ...,"January 13, 2023",https://www.cnbc.com/2023/01/13/pfizer-covid-b...
23,"House targets China, abortion, IRS funding in ...","January 13, 2023",https://www.cnbc.com/2023/01/13/gop-house-targ...
24,Pro Picks: Watch all of Friday's big stock cal...,"January 13, 2023",https://www.cnbc.com/2023/01/13/pro-picks-watc...
25,Rep. Santos admits he 'embellished' his resume...,"January 13, 2023",https://www.cnbc.com/2023/01/13/george-santos-...
26,"6 question on meditation, answered by an expert","January 13, 2023",https://www.cnbc.com/2023/01/13/6-meditation-q...
27,"Trump denies rape in testimony, falsely says a...","January 13, 2023",https://www.cnbc.com/2023/01/13/trump-depositi...
28,House Republicans move to regulate crypto indu...,"January 13, 2023",https://www.cnbc.com/2023/01/13/house-republic...
29,JPMorgan says college-planning firm it bought ...,"January 13, 2023",https://www.cnbc.com/2023/01/13/jpmorgan-says-...

# 8) Write a python program to scrape the details of most downloaded articles from AI in last 90 days.
https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles

Scrape below mentioned details :
i) Paper Title
ii) Authors
iii) Published Date
iv) Paper URL

In [24]:
page = requests.get('https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles')

In [25]:
soup = BeautifulSoup(page.content)

In [26]:
titles = []
for i in soup.find_all('h2',class_="sc-1qrq3sd-1 gRGSUS sc-1nmom32-0 sc-1nmom32-1 btcbYu goSKRg"):
    titles.append(i.text)

In [27]:
authors = []
for i in soup.find_all('span',class_="sc-1w3fpd7-0 dnCnAO"):
    authors.append(i.text)

In [28]:
p_date =[]
for i in soup.find_all('span',class_="sc-1thf9ly-2 dvggWt"):
    p_date.append(i.text)

In [29]:
import pandas as pd

pf = pd.DataFrame({'Titles':titles,'Authors':authors,'Published date':p_date})
pf

,Titles,Authors,Published date
0,Reward is enough,"Silver, David, Singh, Satinder, Precup, Doina,...",October 2021
1,Making sense of raw input,"Evans, Richard, Bošnjak, Matko and 5 more",October 2021
2,Law and logic: A review from an argumentation ...,"Prakken, Henry, Sartor, Giovanni",October 2015
3,Creativity and artificial intelligence,"Boden, Margaret A.",August 1998
4,Artificial cognition for social human–robot in...,"Lemaignan, Séverin, Warnier, Mathieu and 3 more",June 2017
5,Explanation in artificial intelligence: Insigh...,"Miller, Tim",February 2019
6,Making sense of sensory input,"Evans, Richard, Hernández-Orallo, José and 3 more",April 2021
7,Conflict-based search for optimal multi-agent ...,"Sharon, Guni, Stern, Roni, Felner, Ariel, Stur...",February 2015
8,Between MDPs and semi-MDPs: A framework for te...,"Sutton, Richard S., Precup, Doina, Singh, Sati...",August 1999
9,The Hanabi challenge: A new frontier for AI re...,"Bard, Nolan, Foerster, Jakob N. and 13 more",March 2020
10,Evaluating XAI: A comparison of rule-based and...,"van der Waa, Jasper, Nieuwburg, Elisabeth, Cre...",February 2021
11,Argumentation in artificial intelligence,"Bench-Capon, T.J.M., Dunne, Paul E.",October 2007
12,Algorithms for computing strategies in two-pla...,"Bošanský, Branislav, Lisý, Viliam and 3 more",August 2016
13,Multiple object tracking: A literature review,"Luo, Wenhan, Xing, Junliang and 4 more",April 2021
14,Selection of relevant features and examples in...,"Blum, Avrim L., Langley, Pat",December 1997
15,A survey of inverse reinforcement learning: Ch...,"Arora, Saurabh, Doshi, Prashant",August 2021
16,Explaining individual predictions when feature...,"Aas, Kjersti, Jullum, Martin, Løland, Anders",September 2021
17,A review of possible effects of cognitive bias...,"Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Joha...",June 2021
18,Integrating social power into the decision-mak...,"Pereira, Gonçalo, Prada, Rui, Santos, Pedro A.",December 2016
19,“That's (not) the output I expected!” On the r...,"Riveiro, Maria, Thill, Serge",September 2021
20,Explaining black-box classifiers using post-ho...,"Kenny, Eoin M., Ford, Courtney, Quinn, Molly, ...",May 2021
21,Algorithm runtime prediction: Methods & evalua...,"Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyto...",January 2014
22,Wrappers for feature subset selection,"Kohavi, Ron, John, George H.",December 1997
23,Commonsense visual sensemaking for autonomous ...,"Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srik...",October 2021
24,"Quantum computation, quantum theory and AI","Ying, Mingsheng",February 2010

# 9) Write a python program to scrape mentioned details from dineout.co.in :
i) Restaurant name
ii) Cuisine
iii) Location
iv) Ratings
v) Image URL

In [30]:
page = requests.get('https://www.dineout.co.in/delhi-restaurants/buffet-special')

In [31]:
soup = BeautifulSoup(page.content)

In [32]:
# Restaurant name
titles = []
for i in soup.find_all('a',class_="restnt-name ellipsis"):
    titles.append(i.text)

In [33]:
# cuisine name
cuisine = [] 
for i in soup.find_all('span',class_="double-line-ellipsis"):
    cuisine.append(i.text.split('|')[1])

In [34]:
# location name
location = [] 
for i in soup.find_all('div',class_="restnt-loc ellipsis"): 
    location.append(i.text)

In [35]:
# rating name
rating = [] 
for i in soup.find_all('div',class_="restnt-rating rating-4"): 
    rating.append(i.text)

In [36]:
# images name
images = []
for i in soup.find_all("img",class_="no-img"):
    images.append(i.get('data-src'))

In [37]:
import pandas as pd

df = pd.DataFrame({'Titles':titles,'Cuisine':cuisine,'Location':location,'Rating':rating,'Images_url':images})
df

,Titles,Cuisine,Location,Rating,Images_url
0,Castle Barbeque,"Chinese, North Indian","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
1,Jungle Jamboree,"North Indian, Asian, Italian","3CS Mall,Lajpat Nagar - 3, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
2,Cafe Knosh,"Italian, Continental","The Leela Ambience Convention Hotel,Shahdara, ...",4.3,https://im1.dineout.co.in/images/uploads/resta...
3,Castle Barbeque,"Chinese, North Indian","Pacific Mall,Tagore Garden, West Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
4,The Barbeque Company,"North Indian, Chinese","Gardens Galleria,Sector 38A, Noida",4,https://im1.dineout.co.in/images/uploads/resta...
5,India Grill,"North Indian, Italian","Hilton Garden Inn,Saket, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
6,Delhi Barbeque,North Indian,"Taurus Sarovar Portico,Mahipalpur, South Delhi",3.6,https://im1.dineout.co.in/images/uploads/resta...
7,The Monarch - Bar Be Que Village,North Indian,"Indirapuram Habitat Centre,Indirapuram, Ghaziabad",3.8,https://im1.dineout.co.in/images/uploads/resta...
8,Indian Grill Room,"North Indian, Mughlai","Suncity Business Tower,Golf Course Road, Gurgaon",4.3,https://im1.dineout.co.in/images/uploads/resta...