In [2]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\nirma\anaconda3\lib\site-packages (4.7.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio~=0.17 in c:\users\nirma\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sniffio in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: idna in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: outcome in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: sortedcontainers in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\nirma\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: pycparser in c:\users\nirma\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\nirma\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\nirma\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\nirma\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [3]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By

import pandas as pd

import warnings
warnings.filterwarnings("ignore")

Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data

In [4]:
driver=webdriver.Chrome('chromedriver.exe')

In [5]:
url='https://www.naukri.com/'
driver.get(url)

In [6]:
driver.maximize_window()

In [7]:
designation = driver.find_element(By.CLASS_NAME,"suggestor-input")
designation.send_keys('Data Analyst')

In [8]:
location = driver.find_element(By.XPATH,"/html/body/div[1]/div[6]/div/div/div[5]/div/div/div/input") # This XPath input

location.send_keys('Bangalore')

In [9]:
search=driver.find_element(By.CLASS_NAME,"qsbSubmit")
search.click()

In [10]:
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

In [11]:
# Scraping Job title from the given page

title_tags=driver.find_elements(By.XPATH,'//a[@class="title ellipsis"]')
for i in title_tags[0:10]:
    title=i.text
    job_title.append(title)


# Scraping Job Location from the given page

location_tags=driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft locWdth"]')
for i in location_tags[0:10]:
    location=i.text
    job_location.append(location)

# Scraping company name from the given page

company_tags=driver.find_elements(By.XPATH,"//a[@class='subTitle ellipsis fleft']")
for i in company_tags[0:10]:
    company=i.text
    company_name.append(company)

# Scraping Job Experience from the given page

experience_tags=driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft expwdth"]')
for i in experience_tags[0:10]:
    exp=i.text
    experience_required.append(exp)

In [12]:
print(len(job_title),len(job_location),len(company_name),len(experience_required))

10 10 10 10

In [13]:
import pandas as pd

df=pd.DataFrame({'Title':job_title,'Location':job_location,'Company_name':company_name,'Experience':experience_required})
df

,Title,Location,Company_name,Experience
0,"Photon Hires Data Analyst, Night shift# Immedi...","Bangalore/Bengaluru, Chennai",Photon,1-3 Yrs
1,Data Analyst,Bangalore/Bengaluru,Multi Recruit,4-5 Yrs
2,Data Analyst,Hybrid - Bangalore/Bengaluru,Snom Ventures Llp,1-3 Yrs
3,Data Analyst,"Bangalore/Bengaluru, Noida, Gurgaon/Gurugram",Genpact,5-7 Yrs
4,Senior Business Analyst/Data Engineer - Python...,Bangalore/Bengaluru,Huquo Consulting,3-6 Yrs
5,Data Analyst/Senior Analyst - R/SQL/Python,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",The Nikharv Consultancy,3-6 Yrs
6,Manager / Senior Manager - Data Analyst,"Bangalore/Bengaluru, Mumbai, Hyderabad/Secunde...",Huquo Consulting,2-7 Yrs
7,Assistant Manager/Manager - Data Analyst - Ana...,"Bangalore/Bengaluru, Delhi / NCR",Huquo Consulting,6-11 Yrs
8,Data Analyst,Bangalore/Bengaluru,Target,2-4 Yrs
9,Data Analyst - SQL ETL/SSIS - KPO,"Bangalore/Bengaluru, Noida",Huquo Consulting,4-9 Yrs

Q2:Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name. You have to scrape first 10 jobs data. This task will be done in following steps:

In [14]:
driver2=webdriver.Chrome('chromedriver.exe')
driver2.get('https://www.naukri.com/')

In [15]:
driver2.maximize_window()

In [16]:
search_jobs2=driver2.find_element(By.CLASS_NAME,'suggestor-input').send_keys("Data Analyst")

In [17]:
search_location2= driver2.find_element(By.XPATH,"/html/body/div[1]/div[6]/div/div/div[5]/div/div/div/input")
search_location2.send_keys('Bangalore')

In [18]:
search_button2= driver2.find_element("xpath",'/html/body/div[1]/div[6]/div/div/div[6]')
search_button2.click()

In [19]:
title_tags2=driver2.find_elements("xpath",'//a[@class="title ellipsis"]')
job_title2=[]
for i in title_tags2:
    job_title2.append(i.text)
    
loc_tags2=driver2.find_elements("xpath",'//span[@class="ellipsis fleft locWdth"]')
job_loc2=[]
for i in loc_tags2:
    job_loc2.append(i.text)
    
comp_tags2=driver2.find_elements("xpath",'//a[@class="subTitle ellipsis fleft"]')
comp_title2=[]
for i in comp_tags2:
    comp_title2.append(i.text)

In [20]:
print(len(job_title2),len(job_loc2),len(comp_title2))

20 20 20

In [21]:
Data_Analyst_2=pd.DataFrame({'Job Title':job_title2,'Job Location':job_loc2,'Company Name':comp_title2})
Data_Analyst_2[0:10]

,Job Title,Job Location,Company Name
0,"Photon Hires Data Analyst, Night shift# Immedi...","Bangalore/Bengaluru, Chennai",Photon
1,Data Analyst,Bangalore/Bengaluru,Multi Recruit
2,Data Analyst,Hybrid - Bangalore/Bengaluru,Snom Ventures Llp
3,Data Analyst,"Bangalore/Bengaluru, Noida, Gurgaon/Gurugram",Genpact
4,Senior Business Analyst/Data Engineer - Python...,Bangalore/Bengaluru,Huquo Consulting
5,Data Analyst/Senior Analyst - R/SQL/Python,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",The Nikharv Consultancy
6,Manager / Senior Manager - Data Analyst,"Bangalore/Bengaluru, Mumbai, Hyderabad/Secunde...",Huquo Consulting
7,Business Data Analyst,"Bangalore/Bengaluru, Hyderabad/Secunderabad, G...",Acenet
8,Assistant Manager/Manager - Data Analyst - Ana...,"Bangalore/Bengaluru, Delhi / NCR",Huquo Consulting
9,Data Analyst,Bangalore/Bengaluru,Target

Q3: In this question you have to scrape data using the filters available on the webpage as shown below:

In [22]:
driver3=webdriver.Chrome('chromedriver.exe')
driver3.get('https://www.naukri.com/')

In [23]:
search_jobs3=driver3.find_element(By.CLASS_NAME,'suggestor-input')
search_jobs3.send_keys("Data Analyst")

In [24]:
search_button3= driver3.find_element("xpath",'/html/body/div[1]/div[6]/div/div/div[6]')
search_button3.click()

In [25]:
location_filter = driver3.find_element('xpath','/html/body/div[1]/div[4]/div/div/section[1]/div[2]/div[4]/div[2]/div[1]/label/i')
location_filter.click()

In [26]:
salary_checkbox = driver3.find_element("xpath",'/html/body/div[1]/div[4]/div/div/section[1]/div[2]/div[5]/div[2]/div[4]/label/i')
salary_checkbox.click()

In [27]:
title_tags3=driver3.find_elements("xpath",'//a[@class="title ellipsis"]')
job_title3=[]
for i in title_tags3:
    job_title3.append(i.text)
    
loc_tags3=driver3.find_elements("xpath",'//span[@class="ellipsis fleft locWdth"]')
job_loc3=[]
for i in loc_tags3:
    job_loc3.append(i.text)  

sal_3=driver3.find_elements("xpath",'//span[@class="ellipsis fleft expwdth"]')
salary_3=[]
for i in sal_3:
    salary_3.append(i.text)

In [28]:
print(len(job_title2),len(job_loc2),len(comp_title2),len(salary_3))

20 20 20 20

In [29]:
Data_Analyst_3=pd.DataFrame({'Job Title':job_title2,'Job Location':job_loc2,'Company Name':comp_title2, 'Salary':salary_3})
Data_Analyst_3[0:10]

,Job Title,Job Location,Company Name,Salary
0,"Photon Hires Data Analyst, Night shift# Immedi...","Bangalore/Bengaluru, Chennai",Photon,4-5 Yrs
1,Data Analyst,Bangalore/Bengaluru,Multi Recruit,1-3 Yrs
2,Data Analyst,Hybrid - Bangalore/Bengaluru,Snom Ventures Llp,3-6 Yrs
3,Data Analyst,"Bangalore/Bengaluru, Noida, Gurgaon/Gurugram",Genpact,3-6 Yrs
4,Senior Business Analyst/Data Engineer - Python...,Bangalore/Bengaluru,Huquo Consulting,2-7 Yrs
5,Data Analyst/Senior Analyst - R/SQL/Python,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",The Nikharv Consultancy,7-10 Yrs
6,Manager / Senior Manager - Data Analyst,"Bangalore/Bengaluru, Mumbai, Hyderabad/Secunde...",Huquo Consulting,2-4 Yrs
7,Business Data Analyst,"Bangalore/Bengaluru, Hyderabad/Secunderabad, G...",Acenet,7-12 Yrs
8,Assistant Manager/Manager - Data Analyst - Ana...,"Bangalore/Bengaluru, Delhi / NCR",Huquo Consulting,2-7 Yrs
9,Data Analyst,Bangalore/Bengaluru,Target,3-6 Yrs

Q4: Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes:

In [30]:
driver4=webdriver.Chrome('chromedriver.exe')
driver4.get('https://www.flipkart.com/')

In [31]:
popupclose = driver4.find_element("xpath","/html/body/div[2]/div/div/button")
popupclose.click()

In [32]:
search_product=driver4.find_element(By.CLASS_NAME,'_3704LK')
search_product.send_keys("Sunglasses")

In [33]:
search_button4= driver4.find_element(By.CLASS_NAME,'L0Z3Pu')
search_button4.click()

In [34]:
brand=driver4.find_elements("xpath",'//div[@class="_2WkVRV"]')
brand_name=[]
for i in brand[0:35]:
    brand_name.append(i.text)

product=driver4.find_elements("xpath",'//a[@class="IRpwTa"]')
product_desc=[]
for i in product[0:35]:
    product_desc.append(i.text)

price=driver4.find_elements("xpath",'//div[@class="_30jeq3"]')
product_price=[]
for i in price[0:35]:
    product_price.append(i.text)

price_off=driver4.find_elements("xpath",'//div[@class="_3Ay6Sb"]')
Discount=[]
for i in price_off[0:35]:
    Discount.append(i.text)

In [35]:

print(len(brand_name),len(product_desc),len(product_price),len(Discount))

35 35 35 35

In [36]:
product_1=pd.DataFrame({'Brand Name':brand_name,'Product Description':product_desc,'Price':product_price,'Discount':Discount})
product_1[:40]

,Brand Name,Product Description,Price,Discount
0,ROZZETTA CRAFT,"UV Protection, Gradient Rectangular Sunglasses...",₹447,77% off
1,IRUS,UV Protection Retro Square Sunglasses (54),₹637,14% off
2,Fastrack,UV Protection Wayfarer Sunglasses (Free Size),₹619,38% off
3,Elligator,"UV Protection Cat-eye, Retro Square, Oval, Rou...",₹149,75% off
4,SUNBEE,UV Protection Rectangular Sunglasses (Free Size),₹129,87% off
5,LIZA ANGEL,"Riding Glasses, Night Vision Spectacle Sunglas...",₹174,82% off
6,Elligator,UV Protection Round Sunglasses (54),₹229,90% off
7,VINCENT CHASE,"by Lenskart Polarized, UV Protection Cat-eye S...",₹899,55% off
8,SUNBEE,UV Protection Rectangular Sunglasses (Free Size),₹129,87% off
9,PHENOMENAL,UV Protection Retro Square Sunglasses (53),₹129,87% off
10,Elligator,"UV Protection Cat-eye, Retro Square, Oval, Rou...",₹129,87% off
11,Dervin,UV Protection Wayfarer Sunglasses (Free Size),₹224,85% off
12,Fastrack,"Gradient, UV Protection Wayfarer Sunglasses (F...",₹579,35% off
13,SRPM,UV Protection Wayfarer Sunglasses (50),₹149,88% off
14,Elligator,UV Protection Round Sunglasses (53),₹149,85% off
15,ROZZETTA CRAFT,UV Protection Round Sunglasses (Free Size),₹449,77% off
16,VINCENT CHASE,UV Protection Wayfarer Sunglasses (59),₹599,70% off
17,SRPM,"Others Wayfarer, Retro Square Sunglasses (50)",₹129,87% off
18,LIZA ANGEL,"Riding Glasses, UV Protection, Night Vision Sp...",₹129,74% off
19,Silver Kartz,UV Protection Aviator Sunglasses (88),₹266,77% off
20,PIRASO,UV Protection Aviator Sunglasses (58),₹274,89% off
21,New Specs,UV Protection Rectangular Sunglasses (Free Size),₹259,90% off
22,PIRASO,UV Protection Rectangular Sunglasses (52),₹182,88% off
23,RESIST EYEWEAR,"Polarized, Riding Glasses, UV Protection Wayfa...","₹1,399",72% off
24,PIRASO,UV Protection Over-sized Sunglasses (60),₹270,89% off
25,PROVOGUE,"Polarized, UV Protection Rectangular Sunglasse...",₹664,74% off
26,LIZA ANGEL,"UV Protection, Polarized Rectangular Sunglasse...",₹129,87% off
27,SKYZA INDIA,UV Protection Rectangular Sunglasses (Free Size),₹419,65% off
28,PIRASO,UV Protection Aviator Sunglasses (54),₹244,84% off
29,SRPM,"Night Vision, UV Protection Round Sunglasses (54)",₹179,82% off
30,PIRASO,UV Protection Clubmaster Sunglasses (54),₹257,83% off
31,CART2DEAL,"Polarized, Riding Glasses Sports, Wrap-around ...","₹1,244",53% off
32,ROZZETTA CRAFT,"UV Protection, Polarized, Mirrored Rectangular...",₹497,75% off
33,SHAAH COLLECTIONS,UV Protection Aviator Sunglasses (55),₹185,89% off
34,ROZZETTA CRAFT,UV Protection Wayfarer Sunglasses (Free Size),₹649,74% off

In [37]:
page_2=driver4.find_element("xpath",'//a[@class="_1LKTO3"]')
page_2.click()

In [38]:
brand=driver4.find_elements("xpath",'//div[@class="_2WkVRV"]')
brand_name=[]
for i in brand[:37]:
    brand_name.append(i.text)

product=driver4.find_elements("xpath",'//a[@class="IRpwTa"]')
product_desc=[]
for i in product[:37]:
    product_desc.append(i.text)

price=driver4.find_elements("xpath",'//div[@class="_30jeq3"]')
product_price=[]
for i in price[:37]:
    product_price.append(i.text)
    
price_off=driver4.find_elements("xpath",'//div[@class="_3Ay6Sb"]')
Discount=[]
for i in price_off[:37]:
    Discount.append(i.text)

In [39]:
print(len(brand_name),len(product_desc),len(product_price),len(Discount))

37 37 37 37

In [40]:
product_2=pd.DataFrame({'Brand Name':brand_name[:37],'Product Description':product_desc[:37],'Price':product_price[:37],'Discount':Discount[:37]})

In [41]:
page_3=driver4.find_element("xpath",'//a[@class="_1LKTO3"]').click()

In [42]:
brand=driver4.find_elements("xpath",'//div[@class="_2WkVRV"]')
brand_name=[]
for i in brand[:36]:
    brand_name.append(i.text)
    
product=driver4.find_elements("xpath",'//a[@class="IRpwTa"]')
product_desc=[]
for i in product[:36]:
    product_desc.append(i.text)
    
price=driver4.find_elements("xpath",'//div[@class="_30jeq3"]')
product_price=[]
for i in price[:36]:
    product_price.append(i.text)
    
price_off=driver4.find_elements("xpath",'//div[@class="_3Ay6Sb"]')
Discount=[]
for i in price_off[:36]:
    Discount.append(i.text)
    
product_3=pd.DataFrame({'Brand Name':brand_name[:36],'Product Description':product_desc[:36],'Price':product_price[:36],'Discount':Discount[:36]})

In [43]:
print(len(brand_name),len(product_desc),len(product_price),len(Discount))

36 36 36 36

In [44]:
page_4=driver4.find_element("xpath",'//a[@class="_1LKTO3"]').click()

In [45]:
brand=driver4.find_elements("xpath",'//div[@class="_2WkVRV"]')
brand_name=[]
for i in brand[:39]:
    brand_name.append(i.text)
    
product=driver4.find_elements("xpath",'//a[@class="IRpwTa"]')
product_desc=[]
for i in product[:39]:
    product_desc.append(i.text)
    
price=driver4.find_elements("xpath",'//div[@class="_30jeq3"]')
product_price=[]
for i in price[:39]:
    product_price.append(i.text)
    
price_off=driver4.find_elements("xpath",'//div[@class="_3Ay6Sb"]')
Discount=[]
for i in price_off[:39]:
    Discount.append(i.text)
    
product_4=pd.DataFrame({'Brand Name':brand_name[:39],'Product Description':product_desc[:39],'Price':product_price[:39],'Discount':Discount[:39]})

In [46]:
print(len(brand_name),len(product_desc),len(product_price),len(Discount))

39 39 39 39

In [47]:
product=pd.concat([product_1,product_2,product_3], ignore_index=True)

In [48]:
print(len(product))

108

In [49]:
product[:100]

,Brand Name,Product Description,Price,Discount
0,ROZZETTA CRAFT,"UV Protection, Gradient Rectangular Sunglasses...",₹447,77% off
1,IRUS,UV Protection Retro Square Sunglasses (54),₹637,14% off
2,Fastrack,UV Protection Wayfarer Sunglasses (Free Size),₹619,38% off
3,Elligator,"UV Protection Cat-eye, Retro Square, Oval, Rou...",₹149,75% off
4,SUNBEE,UV Protection Rectangular Sunglasses (Free Size),₹129,87% off
...,...,...,...,...
95,RESIST EYEWEAR,"Polarized, Riding Glasses, UV Protection Wayfa...","₹1,399",72% off
96,PIRASO,UV Protection Rectangular Sunglasses (52),₹182,88% off
97,PIRASO,UV Protection Over-sized Sunglasses (60),₹270,89% off
98,LIZA ANGEL,"UV Protection, Polarized Rectangular Sunglasse...",₹129,87% off
99,SKYZA INDIA,UV Protection Rectangular Sunglasses (Free Size),₹419,65% off

Q5: Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to go the link: https://www.flipkart.com/apple-iphone-11-black-64-gb/product%02reviews/itm4e5041ba101fd pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market place=FLIPKART

In [50]:
driver5=webdriver.Chrome('chromedriver.exe')
driver5.get('https://www.flipkart.com/')

In [51]:
pop_close = driver5.find_element("xpath","/html/body/div[2]/div/div/button").click()

In [52]:
search_product2=driver5.find_element(By.CLASS_NAME,'_3704LK')
search_product2.send_keys("nokiaC2")

In [53]:
search_button5= driver5.find_element(By.CLASS_NAME,'L0Z3Pu')
search_button5.click()

In [54]:

driver5.get('https://www.flipkart.com/nokia-c-30-green-32-gb/p/itm47608c0b7481f?pid=MOBG7R5FR29FFHYF&lid=LSTMOBG7R5FR29FFHYF0K3LZ2&marketplace=FLIPKAR')

In [55]:
All_reviews=driver5.find_element("xpath",'//div[@class="_3UAT2v _16PBlm"]').click()

In [56]:
rating_tag1=driver5.find_elements("xpath",'//div[@class="_3LWZlK _1BLPMq"]')
rating1=[]
for i in rating_tag1[:6]:
    rating1.append(i.text)

review_sum1=driver5.find_elements("xpath",'//p[@class="_2-N8zT"]')
review1=[]
for i in review_sum1[:6]:
    review1.append(i.text)

review_full1=driver5.find_elements("xpath",'//div[@class="t-ZTKy"]')
full_review1=[]
for i in review_full1[:6]:
    full_review1.append(i.text.replace('\n',' , '))

In [57]:
print(len(rating1),len(review1),len(full_review1))

6 6 6

In [58]:
Nokia_reviews1=pd.DataFrame({'Rating':rating1,'Review Summary':review1,'Full Review':full_review1})

In [59]:
Nokia_reviews1=pd.concat([Nokia_reviews1], ignore_index=True)
Nokia_reviews1[:6]

,Rating,Review Summary,Full Review
0,5,Brilliant,Buying a Nokia refreshed my memories of the go...
1,5,Just wow!,Good product
2,5,Did not meet expectations,Not that good
3,3,Just wow!,Good
4,5,Fair,Battery gets very heat fast
5,4,Best in the market!,Good

Q6: Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field

In [60]:
driver6=webdriver.Chrome('chromedriver.exe')
driver6.get('https://www.flipkart.com/')

In [62]:
pop_close = driver6.find_element("xpath","/html/body/div[2]/div/div/button").click()

In [63]:
search_product6=driver6.find_element(By.CLASS_NAME,'_3704LK').send_keys("sneakers")

In [ ]:
search_button6= driver6.find_element(By.CLASS_NAME,'L0Z3Pu').click()

In [ ]:
brand6=driver6.find_elements("xpath",'//div[@class="_2WkVRV"]')
brand_name6=[]
for i in brand6:
    brand_name6.append(i.text)
    
product6=driver6.find_elements("xpath",'//a[@class="IRpwTa"]')
product_desc6=[]
for i in product6:
    product_desc6.append(i.text)
    
price6=driver6.find_elements("xpath",'//div[@class="_30jeq3"]')
product_price6=[]
for i in price6:
    product_price6.append(i.text)
    
price_off6=driver6.find_elements("xpath",'//div[@class="_3Ay6Sb"]')
Discount6=[]
for i in price_off6:
    Discount6.append(i.text)

In [ ]:
print(len(product_desc6),len(product_price6),len(Discount6),len(brand_name6))

In [ ]:
sneaker1=pd.DataFrame({'Brand Name':brand_name6[:30],'Product Description':product_desc6[:30], 'Product Price':product_price6[:30],'Discount':Discount6})

In [ ]:
page_2=driver6.find_element("xpath",'//a[@class="_1LKTO3"]').click()

In [ ]:
brand6=driver6.find_elements("xpath",'//div[@class="_2WkVRV"]')
brand_name6=[]
for i in brand6:
    brand_name6.append(i.text)
    
product6=driver6.find_elements("xpath",'//a[@class="IRpwTa"]')
product_desc6=[]
for i in product6:
    product_desc6.append(i.text)
    
price6=driver6.find_elements("xpath",'//div[@class="_30jeq3"]')
product_price6=[]
for i in price6:
    product_price6.append(i.text)
    
price_off6=driver6.find_elements("xpath",'//div[@class="_3Ay6Sb"]')
Discount6=[]
for i in price_off6:
    Discount6.append(i.text)
    
sneaker2=pd.DataFrame({'Brand Name':brand_name6[:30],'Product Description':product_desc6[:30], 'Product Price':product_price6[:30],'Discount':Discount6[

In [ ]:
page_3=driver6.find_element("xpath",'//a[@class="_1LKTO3"]').click()

Q7: Go to webpage https://www.amazon.in/ Enter “Laptop” in the search field and then click the search icon. Then set CPU Type filter to “Intel Core i7” as shown in the below image:

In [65]:
driver = webdriver.Chrome(r"C:\Users\Sunny\Downloads\chromedriver_win32\chromedriver.exe")

In [68]:
url = 'https://www.amazon.in/'
driver.get(url)

In [67]:
search_product_name=driver.find_element(By.CLASS_NAME,'nav-input')
search_product_name.send_keys('Laptops')

In [69]:
Page=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
Page.click()

In [70]:
filter1=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[6]/ul[2]/li[14]/span/a/div')
filter1.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[6]/ul[2]/li[14]/span/a/div"}
  (Session info: chrome=109.0.5414.75)
Stacktrace:
Backtrace:
	(No symbol) [0x00716643]
	(No symbol) [0x006ABE21]
	(No symbol) [0x005ADA9D]
	(No symbol) [0x005E1342]
	(No symbol) [0x005E147B]
	(No symbol) [0x00618DC2]
	(No symbol) [0x005FFDC4]
	(No symbol) [0x00616B09]
	(No symbol) [0x005FFB76]
	(No symbol) [0x005D49C1]
	(No symbol) [0x005D5E5D]
	GetHandleVerifier [0x0098A142+2497106]
	GetHandleVerifier [0x009B85D3+2686691]
	GetHandleVerifier [0x009BBB9C+2700460]
	GetHandleVerifier [0x007C3B10+635936]
	(No symbol) [0x006B4A1F]
	(No symbol) [0x006BA418]
	(No symbol) [0x006BA505]
	(No symbol) [0x006C508B]
	BaseThreadInitThunk [0x75B87D69+25]
	RtlInitializeExceptionChain [0x7700BB9B+107]
	RtlClearBits [0x7700BB1F+191]

In [71]:
title1=[]
#scrapting all the tags brand names
lap=driver.find_elements(By.CLASS_NAME,"a-size-mini")

#displaying 10 tags extracted above into text 
for i in lap:
    title1.append(i.text)
title1[0:10]

['Up to',
 '36',
 '% off',
 'Ends in',
 '02:54:50',
 '02:54:49',
 'Up to',
 '77',
 '% off',
 'Deal of the Day']

In [72]:
price_laptop=[]
#scrapting all the tags brand names
lap_price=driver.find_elements(By.CLASS_NAME,"a-price-whole")

#displaying 10 tags extracted above into text 
for i in lap_price:
    price_laptop.append(i.text)
price_laptop[0:10]

[]

In [73]:
import pandas as pd
df = pd.DataFrame({'Laptop name':title1[0:10],'Price':price_laptop[0:10]})
df

ValueError: All arrays must be of the same length